apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mybinding-rolebinding
subjects:
- kind: ServiceAccount
  name: myactorclient
  namespace: binding-namespace
roleRef:
  kind: Role
  name: mybinding-role
  apiGroup: ""
