{{- if .Values.virtualService.create -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: serviceb
  labels:
    {{- include "serviceb.labels" . | nindent 4 }}
spec:
  {{- with .Values.virtualService.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}